[package]
name = "romfile-decode"
version = "0.1.0"
edition = "2021"

[dependencies]
aes = "0.8.4"
base64 = "0.22.1"
cbc = "0.1.2"
quick-xml = { version = "0.37.1", features = ["serialize"] }
serde_json = "1.0.133"
